[error] scala.MatchError: org.apache.logging.log4j.simple.SimpleLoggerContext@5cbaf868 (of class org.apache.logging.log4j.simple.SimpleLoggerContext)
[error] 	at sbt.util.LogExchange.logger(LogExchange.scala:28)
[error] 	at sbt.internal.LogManager$.defaultLogger(LogManager.scala:137)
[error] 	at sbt.internal.LogManager$DefaultLogManager.apply(LogManager.scala:104)
[error] 	at sbt.internal.LogManager$.$anonfun$construct$1(LogManager.scala:52)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:178)
[error] 	at sbt.std.TaskStreams.log(Streams.scala:85)
[error] 	at sbt.std.TaskStreams.log$(Streams.scala:85)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:136)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:136)
[error] 	at sbt.Classpaths$.$anonfun$depMap$1(Defaults.scala:2711)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:835)
